include:
  # Planck
  - board: planck//zmk
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y

  # Totem + XIAO BLE
  - board: xiao_ble//zmk
    shield: totem_left
    artifact-name: totem_left
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem_right
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y

  # EyeLash Corne
  - board: eyelash_corne_left
    shield: nice_view
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: nice_view
    #snippet: zmk-usb-logging
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_corne_studio_left
  - board: eyelash_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging
