include:
  # Planck
  - board: planck//zmk
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y

  # Totem + XIAO BLE
  - board: xiao_ble//zmk
    shield: totem_left
    artifact-name: totem_left
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem_right
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y

  # EyeLash Corne
  - board: nice_nano@2//zmk
    shield: eyelash_corne_left nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: eyelash_corne_studio_left
  - board: nice_nano@2//zmk
    shield: eyelash_corne_right nice_view
    #snippet: zmk-usb-logging

  # KLOR
  - board: nice_nano@2//zmk
    shield: klor_left
    artifact-name: klor_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano@2//zmk
    shield: klor_right
    artifact-name: klor_right
