manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cfergeau
      url-base: https://github.com/cfergeau
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3-branch
      import: app/west.yml
    - name: zmk-module-4pplet
      remote: cfergeau
      clone-depth: 1
      revision: main
    - name: zmk-config-corne-eyelash
      remote: cfergeau
      clone-depth: 1
      revision: module
    - name: zmk-helpers
      remote: urob
      revision: main
  self:
    path: config
